### ISSUE TITLE
Building with XL on an IBM AC922 system

### ISSUE THREAD

**Issue by cwsmith** [hypre-space/hypre#89]
I'm attempting to install Hypre on an IBM AC922 (i.e., Summit, Sierra, Lassen) and would like to use the IBM XL 16.1 compilers and Spectrum MPI 10.3.  My first attempt at the install was through Spack. That build failed while trying to compile the openblas dependency; [openblas does not support XL](https://github.com/xianyi/OpenBLAS/issues/2333).  My Spack 'spec' for the Hypre install is:

```
hypre@2.13.0%xl@16.1.1~complex~debug~int64~internal-superlu~mixedint+mpi~openmp+shared~superlu-dist
```

The Spack package file for Hypre is here:
https://github.com/spack/spack/blob/v0.13.3/var/spack/repos/builtin/packages/hypre/package.py

Is there a way through Spack, or otherwise, to build Hypre with the XL compilers that produces an install similar to the one requested via Spack?

**Comment by victorapm** [comment]
Hi @cwsmith,

you can use netlib's implementation of BLAS/LAPACK instead. I've tried also ESSL, but apparently there's a problem with it in spack, see https://github.com/spack/spack/issues/7901.

Make sure that Spectrum MPI and Netlib-lapack are listed in your *packages.yaml* file. It will look like:
```
packages:
  spectrum-mpi:
    paths:
       spectrum-mpi@2019.12.23%xl arch=linux-rhel7-ppc64le: $MPI_ROOT
    buildable: false
  netlib-lapack:
    paths:
       netlib-lapack@3.8.0%xl arch=linux-rhel7-ppc64le: $LAPACK_DIR
    version: [3.8.0]
    buildable: false
  all:
    providers:
      mpi: [spectrum-mpi]
      blas: [netlib-lapack]
```

In Lassen, you would do:
```
module load spectrum-mpi
module load lapack
spack install hypre@2.13.0%xl@16.1~complex~debug~int64~internal-superlu~mixedint+mpi~openmp+shared~superlu-dist
```

Alternatively, you can download a tarball of hypre at https://github.com/hypre-space/hypre/releases and run:
```
cd hypre/src
./configure --enable-shared
make -j $NP
```

This would produce an install similar to the one requested via Spack.
